packages/database/package.json, packages/database/src/api/degree/add.ts, packages/database/src/api/degree/getOne.ts, packages/database/src/api/degree/save.ts, packages/database/src/api/degree/show.ts, packages/database/src/api/user/add.ts, packages/database/src/api/user/save.ts, packages/database/src/entity/Degree.ts, packages/database/src/entity/User.ts, packages/database/src/functions/degree.ts, packages/database/src/functions/user.ts, packages/database/tests/entity/user.test.ts, packages/database/types/modtree.d.ts
- Rename add to save
- Rename methods to use convention
- Rename `package.json` script keys to use convention
=> Refactor of Degree and User methods/api/functions

packages/database/src/entity/Degree.ts, packages/database/src/entity/User.ts, packages/database/types/modtree.d.ts
standardized constructor used in `User` and `Degree`
=> Standardize constructors

packages/database/src/api/module/get/codes.ts, packages/database/src/api/module/get/index.ts, packages/database/src/api/module/pull.ts, packages/database/src/api/moduleCondensed/fetch.ts, packages/database/src/api/moduleCondensed/get.ts, packages/database/src/api/user/canTakeModule.ts, packages/database/src/api/user/save.ts, packages/database/tests/entity/user.test.ts
Fixes #43
Temporarily retiring API (at least for Module and User), as it is currently not necessary
Will retire Degree API
=> fix stray user function code

packages/database/src/controller/ModuleCondensed.ts
=> fix wrong import

packages/database/src/entity/index.ts
=> add missing index.ts file to fix imports

packages/database/src/entity/Degree.ts, packages/database/tests/configs/jest.config.ts, packages/database/tests/degree.test.ts
Implements `Degree.insertModules`
=> Degree.insertModules

packages/database/.eslintrc.js, packages/database/package.json, packages/database/src/repository/DAG.ts, packages/database/src/repository/Degree.ts, packages/database/src/repository/Module.ts, packages/database/src/repository/User.ts, packages/database/tests/.eslintrc.js, packages/database/tests/base.test.ts, packages/database/tests/configs/jest.config.ts, packages/database/tests/configs/sequencer.js, packages/database/tests/dag.test.ts, packages/database/tests/degree.test.ts, packages/database/tests/environment.ts, packages/database/tests/module-condensed-pull.test.ts, packages/database/tests/module-condensed.test.ts, packages/database/tests/module-pull.test.ts, packages/database/tests/user.test.ts, packages/database/tsconfig.json, yarn.lock
=> lint tests

packages/database/src/repository/DAG.ts, packages/database/src/utils/string.ts, packages/database/tests/dag.test.ts, packages/database/types/modtree.d.ts
- Fixed `DAGInitProps` incorrect type definition
- `DAGInitProps` -> `Init.DAGProps`
- Removed undefined check of `getModuleLevel`
=> Misc cleans

packages/database/package.json, packages/database/src/repository/DAG.ts, packages/database/src/repository/User.ts, packages/database/src/utils/array.ts, packages/database/src/utils/object.ts, packages/database/tests/configs/all.config.ts, packages/database/tests/configs/jest.config.ts, packages/database/tests/dag.test.ts, packages/database/tests/degree.test.ts, packages/database/tests/init.ts, packages/database/tests/module.test.ts, packages/database/tests/user.test.ts, packages/database/tests/utils.test.ts
Handles edge cases with tests written
`Module.preclusion` is a string and the data right now is quite inconsistent, so not checking for preclusion in `User.canTakeModule`.
=> Handle edge/invalid cases for repository methods

apps/web/components/Search.tsx, apps/web/components/module-search/Results.tsx, apps/web/components/module-search/Selected.tsx, apps/web/contexts/ModuleContext.tsx, apps/web/pages/index.tsx, apps/web/types/index.d.ts
module selector now keeps track of what modules you've selected.
=> add a list of selected modules

packages/database/.sql/README.md
- Adds a module-only sql dump (Module, ModuleCondensed)
- Adds a README in `.sql/` that explains the states of each `.sql`
=> Module only dump

.github/workflows/ci.yml, .gitignore
* CI runs now read from Turbo cache
=> turbocharge ci

packages/database/src/entity/User.ts, packages/database/src/migrations/migration_2022-05-25_16:53:43.ts, packages/database/src/repository/Degree.ts, packages/database/src/repository/User.ts, packages/database/tests/init.ts, packages/database/tests/user/degreeMethods.test.ts, packages/database/tests/user/setup.ts
- User.addDegree
- User.findDegree
- User.removeDegree
=> User degree relations

packages/database/src/utils/array.ts
Add back deleted file in #123
CI should run and pass
=> fix: add back missing file

.github/workflows/deploy.yml
- removes the git history before sending for deployment
- this helps my github contributions not be over-inflated.
=> ci: deploy with only one commit

apps/web/components/buttons/FloatingUserButton/SignedIn.tsx, apps/web/components/header/Results.tsx, apps/web/components/header/SearchBar.tsx, apps/web/package.json, apps/web/postcss.config.js, apps/web/project.json, apps/web/store/modal.ts, apps/web/tailwind.config.js, apps/web/tsconfig.json, libs/entity/src/Degree.ts, libs/entity/src/Graph.ts, libs/entity/src/Module.ts, libs/entity/src/ModuleCondensed.ts, libs/entity/src/User.ts, libs/entity/src/index.ts
In preparation for #167.
- use `@nrwl/next:build` to build web
- use `@nrwl/next:server` to serve web
This was necessary to facilitate importing more things into the web repo.
- try to build web with `nx build web`
- try to serve frontend with `yarn serve` from root
=> feat(nx): build + serve web with builtin Nx executors

apps/server/src/controller/ModuleCondensed.ts, apps/server/src/server/routes.ts, apps/web/components/modals/UserProfile/ModulesDone.tsx, apps/web/components/modals/UserProfile/index.tsx, apps/web/store/base.ts, libs/postman/modules/find-by-codes.ts, libs/postman/package.json, libs/postman/user/create.ts, libs/repo-module/src/ModuleCondensed.ts, libs/repo-module/test/module-condensed/find-by-codes.test.ts, libs/types/src/repository.ts
Check Floating user icon > Your profile > Modules Done
=> User profile modules done

apps/docs/jest.config.ts, apps/docs/project.json, apps/docs/test/init.ts, apps/docs/test/schema.test.ts, apps/docs/tsconfig.json, apps/docs/tsconfig.spec.json, apps/docs/types.d.ts, apps/docs/utils/schema.ts, libs/test-env/src/jest-matchers.ts, tsconfig.base.json, workspace.json
- Added test for `generateSchema` util
- `yarn nx run docs:test`
=> test: add test for generateSchema

apps/docs/components/ParameterList.tsx, apps/docs/data/module-condensed/find-by-codes.ts, apps/docs/data/module-condensed/get.ts, apps/docs/data/module-condensed/index.ts, apps/docs/data/module-condensed/list.ts, apps/docs/data/module/get.ts, apps/docs/pages/reference/module-condensed.mdx, apps/docs/test/schema.test.ts, apps/docs/types.d.ts, apps/docs/utils/schema.ts, apps/server/src/routes/module.ts, apps/web/components/header/search-bar/lib.ts, apps/web/ui/search-box.tsx
- Standardizes `Module` and `ModuleCondensed` API, updating all references
- Update `generateSchema` to handle top-level array responses
- Update `Module` and `ModuleCondensed` API docs
- Regular testing
- Check docs
=> feat: standardize Module and ModuleCondensed API

apps/docs/pages/docs/developer-guide/prerequisites.mdx, apps/server/src/controller/ModuleCondensed.ts, apps/server/src/controller/User.ts, apps/server/src/routes/module.ts, libs/repo-degree/test/delete.test.ts, libs/repo-user/src/index.ts, libs/repo-user/test/degree-methods.test.ts, libs/types/src/controller.ts, libs/types/src/repository.ts
- Remove unused `prerequisites.mdx` in docs
- `User.addDegree` repo method is now `User.insertDegrees`
- `User.insertDegrees` controller method now uses `User.insertDegrees` repo method
- Update controller types for User, Degree, Module, ModuleCondensed
Regular testing
=> feat: misc small changes

apps/server/src/app.ts, apps/server/src/controller/Degree.ts, apps/server/src/controller/Graph.ts, apps/server/src/controller/Module.ts, apps/server/src/controller/ModuleCondensed.ts, apps/server/src/controller/User.ts, apps/server/src/controller/base.ts, apps/server/src/main.ts, libs/repo-api/src/index.ts
- allows us to swap out the Api class passed into the server for future mock testing
=> feat: make server app take in custom api

apps/docs/components/Method.tsx, apps/docs/components/ParameterList.tsx, apps/docs/data/degree/create.ts, apps/docs/data/degree/delete.ts, apps/docs/data/degree/get.ts, apps/docs/data/graph/get.ts, apps/docs/data/module-condensed/find-by-codes.ts, apps/docs/data/module-condensed/get.ts, apps/docs/data/module/get.ts, apps/docs/data/user/delete.ts, apps/docs/data/user/get-by-primary-keys.ts, apps/docs/data/user/get-full.ts, apps/docs/data/user/get.ts, apps/docs/data/user/insert-degrees.ts, apps/docs/types.d.ts, apps/server/src/controller/User.ts, apps/server/src/routes/user.ts, libs/postman/user/by-email.ts
- In docs, `POST` methods have body parameters instead of query parameters
- Fixes `User.getByPrimaryKeys` controller
Try getting a user by email in postman
=> feat: body param docs

libs/repo-pull/src/Module.ts, libs/repo-pull/test/module.test.ts
Minor changes to #221
Regular testing
=> fix: edits for PR #221

apps/docs/package.json, package.json, yarn.lock
Fixes #270 
- remove yarn workspaces,
- check that docs deployment still works
=> fix: get backend deployment up again.

apps/server/src/main.ts, docker/Dockerfile.server, docker/docker-compose.yml, docker/up, package.json, scripts/serve.sh
- used to be 2.2G, is now 1.5G
=> feat: reduce docker build size

docker/Dockerfile.postgres, docker/docker-compose.yml, docker/dump, libs/migrations/snapshots/1657375809467-mod3_to_20220709.ts, libs/migrations/snapshots/index.ts, libs/migrations/src/scripts/empty-string-to-array.test.ts, libs/repos/src/user/test/get-postreqs.test.ts, libs/test-env/src/temp.test.ts, libs/typeorm-config/src/index.ts, scripts/postgres.sh
=> chore: synchronize snapshot and production schema

apps/server/test/graph/[POST].test.ts, apps/web/components/user-profile/degrees/add-new.tsx, apps/web/components/user-profile/graphs/add-new.tsx, apps/web/components/user-profile/graphs/main.tsx, apps/web/ui/search/degree/degree-picker.tsx, apps/web/ui/search/graph/graph-picker.tsx, libs/auto-docs/src/init.ts, libs/postman/graphs/create.ts, libs/repos/src/api/repo.ts, libs/repos/src/graph/get-modules.ts, libs/repos/src/graph/repo.ts, libs/repos/src/graph/test/get-suggest-modules-params.test.ts, libs/repos/src/graph/test/initialize/base.test.ts, libs/repos/src/graph/test/initialize/flow-nodes.test.ts, libs/repos/src/graph/test/toggle.test.ts, libs/repos/src/graph/test/update-frontend/all-nodes.test.ts, libs/repos/src/graph/test/update-frontend/one-node.test.ts, libs/repos/src/user/test/graph/insert-graphs.test.ts, libs/repos/src/user/test/graph/set-main-graph/saved-degree.test.ts, libs/repos/src/user/test/graph/set-main-graph/unsaved-degree.test.ts, libs/test-env/src/init.ts, libs/types/src/init-props.ts, libs/utils/src/empty-init.ts
- Remove `modulesPlacedCodes`, `modulesHiddenCodes`, `pullAll` from `InitGraphProps`
- Remove pull all option in add graph page
- Display user modules in add graph page
- Regular testing
=> feat: further setup for add graph page

libs/repos/src/degree/test/initialize.test.ts, libs/repos/src/module/__mocks__/index.ts, libs/repos/src/module/__mocks__/repo.ts, libs/repos/src/module/repo.ts, libs/repos/src/module/test/can-take-module.json, libs/repos/src/module/test/can-take-module.test.ts, libs/repos/src/module/test/database.json, libs/repos/src/module/test/get-postreqs.test.ts, libs/repos/src/user/test/initialize.test.ts, libs/types/src/repository.ts
- now, you can pass in a mini json object that represents data in the database.
=> test(module): add mock ability to fake a database

apps/web/api/graph.ts, apps/web/api/user.ts, apps/web/components/flow/pane.tsx, apps/web/components/user-profile/graphs/add-new.tsx, apps/web/pages/_app.tsx
- Can create new graph 🔥
- (Previously) can toggle graph, now testable
- Fit view upon any graph change
- Try creating a new graph. This persists.
- Try changing the main graph. This causes the nodes and edges to update, and the view to fit the graph.
=> feat: add graph panel

apps/web/components/menu-items.ts
Implement mark as done/doing menu functionality
- Insert CS2030 into empty graph. It should be red
- Try marking CS2030 as done. It should turn green
- Check user modules done. It should include CS2030
=> feat(frontend): mark done/doing functionality

.github/workflows/deploy.yml, .github/workflows/release.yml
|                |   <h3>Production 🚀</h3>   |    <h3>Development 📦</h3>    |
| :------------: | :------------------------: | :---------------------------: |
|    website     |   [`modtree.vercel.app`]   |  [`modtree-dev.vercel.app`]   |
|     server     | [`modtree.herokuapp.com`]  | [`modtree-dev.herokuapp.com`] |
|    database    |           same →           |            ← same             |
| deploy trigger | GitHub Release/Pre-release |        Merge to `main`        |
[`modtree.vercel.app`]: https://modtree.vercel.app
[`modtree-dev.vercel.app`]: https://modtree-dev.vercel.app
[`modtree.herokuapp.com`]: https://modtree.herokuapp.com
[`modtree-dev.herokuapp.com`]: https://modtree-dev.herokuapp.com
=> feat(deploy): set up a separate deployment for development

apps/web/components/flow/pane.tsx, apps/web/utils/rehydrate.ts
Fixes #325
**404s checking**
- Run `yarn dev` at root
- Go to http://localhost:3000
- Browser console should not have any 404s
**Cypress tests**
- All e2e tests should pass except for module-nodes, likely because of some other issue
=> fix: wrap api calls with path param check

apps/docs/next.config.js, apps/docs/package.json, apps/docs/yarn.lock
get `yarn dev:docs` to work again
=> fix: local docs serving

apps/server/src/trpc/graph.ts, apps/web/api/graph.ts, apps/web/components/graph-title.tsx, apps/web/components/user-profile/graphs/add-new.tsx, apps/web/components/user-profile/graphs/edit.tsx, apps/web/components/user-profile/graphs/index.tsx, apps/web/components/user-profile/graphs/main.tsx, apps/web/pages/index.tsx, apps/web/store/initial-state.ts, apps/web/store/search.ts, apps/web/store/types.d.ts, apps/web/types/index.d.ts, apps/web/ui/search/graph/graph-picker.tsx, apps/web/ui/settings/lists/rows.tsx, libs/repos/src/graph/repo.ts, libs/types/src/repository.ts, libs/utils/src/module/check-tree.spec.ts
- Graph picker is displayed at the main page, allowing a user to see current graph, and switch between graphs
- Can edit title of any graph
Regular testing
=> feat: change graph title

apps/web-e2e/cypress/integration/sign-in.cy.ts, apps/web-e2e/cypress/integration/user-profile/modules.cy.ts, apps/web-e2e/cypress/support/commands.ts, apps/web-e2e/cypress/utils/constants.ts, apps/web/utils/trpc.ts
- Fixes trpc base url
- Add flexibility for e2e test
=> fix: trpc base url

apps/web-e2e/cypress/integration/graph/add-and-remove.cy.ts, apps/web-e2e/cypress/integration/search.cy.ts, apps/web-e2e/cypress/integration/sign-in.cy.ts, apps/web-e2e/cypress/integration/user-profile/modules.cy.ts, apps/web-e2e/cypress/support/commands.ts, apps/web/components/buttons/floating-user-button.tsx, apps/web/components/modals/module-info/index.tsx, apps/web/components/user-profile/modules/main.tsx, apps/web/ui/buttons/close.tsx, apps/web/ui/modal/index.tsx, apps/web/ui/modal/panel.tsx
- Module test checks that the test user does not have LAC1201 and LAC2201 before doing the test
- Module test does not depend on a hardcoded constant
- Graph test checks that the graph does not have MA2104 before doing the test
- Refactoring
Run E2E tests
=> test(e2e): refactor and improve quality of current tests

apps/web-e2e/cypress/integration/graph/add-and-remove.cy.ts, apps/web-e2e/cypress/integration/user-profile/modules.cy.ts, apps/web/store/functions.ts
- Fix: remove module from modules done/doing
- Update graph test for new store location
- Improve reliability of module tests
Try removing module from modules done/doing and save
=> fix: edits for PR #353

apps/web/components/user-profile/degrees/add-new.tsx, apps/web/components/user-profile/degrees/edit.tsx, apps/web/components/user-profile/degrees/index.tsx, apps/web/components/user-profile/graphs/edit.tsx, apps/web/store/functions.ts, apps/web/ui/search/graph/graph-picker.tsx, apps/web/utils/graph/index.ts, scripts/yarn.sh
=> fix: state related issues

apps/web/store/initial-state.ts, apps/web/store/modal.ts, apps/web/store/types.d.ts, apps/web/types/index.d.ts, apps/web/ui/menu/context-menu.tsx
Fixes #360 
Tiny caveat: requires 2 `dispatch` calls
=> fix: always keep context menu in viewport

apps/web-e2e/cypress/integration/graph/add-and-remove.cy.ts, apps/web-e2e/cypress/integration/graph/new-graph.cy.ts, apps/web-e2e/cypress/support/commands.ts, apps/web/components/user-profile/graphs/add-new.tsx, apps/web/ui/buttons/close.tsx, apps/web/ui/buttons/delete.tsx
- `cy.addGraph()` takes in a title
- `cy.removeGraph()` also takes in a title
- in preparation for future graph testing
- run the `new-graph.cy.ts` test
=> test(e2e): add commands to add/remove graph

apps/web-e2e/cypress/integration/graph/new-graph.cy.ts
=> test(e2e): adding a new module to a new graph

apps/docs/package.json, apps/docs/yarn.lock, package.json, tests.json, yarn.lock
- Move `swagger-ui-react` to docs `package.json`
=> fix: docs build

apps/web-e2e/cypress/integration/graph/add-and-remove.cy.ts, apps/web-e2e/cypress/integration/graph/new-graph.cy.ts, apps/web-e2e/cypress/integration/user-profile/degrees.cy.ts, apps/web-e2e/cypress/integration/user-profile/modules.cy.ts, apps/web-e2e/cypress/support/commands.ts, apps/web-e2e/cypress/support/login.ts, libs/repos/src/api/repo.ts
- User is reset before running any state changing tests
- fix: `resetUser()` did not clear graph modules correctly
- fix: degree test
All tests pass
=> test(e2e): all current cypress tests pass

apps/web-e2e/cypress/integration/graph/initial-module-state/doing.cy.ts, apps/web-e2e/cypress/integration/graph/initial-module-state/done.cy.ts, apps/web-e2e/cypress/integration/graph/initial-module-state/planned-cannot-take.cy.ts, apps/web-e2e/cypress/integration/graph/initial-module-state/planned.cy.ts, apps/web-e2e/cypress/integration/graph/update-module-state.cy.ts, apps/web/components/flow/module-node.tsx, apps/web/store/functions.ts
- Fixes #377
- Add E2E tests for inserting all initial module states (except suggested)
- Add E2E test for updating a placed module's state
E2E tests pass
=> fix: save redrawn graph to DB

scripts/run-tests/handle-args.ts, scripts/run-tests/help.ts
Upon running `yarn test`,
- (new) Print command usage text 
- Print workspace tests
- (new) Print groups
Run `yarn test` and see the changes
=> feat: improve help text for test runner

apps/docs/pages/docs/developer-guide/build-prerequisites.mdx, apps/docs/pages/docs/developer-guide/deployment.mdx, apps/docs/pages/docs/developer-guide/meta.json, apps/docs/pages/docs/developer-guide/setup.mdx, apps/docs/pages/docs/developer-guide/tech-stack.mdx, apps/docs/pages/docs/glossary.mdx
- Update developer guide
- Update tech stack
=> docs: update dev guide and tech stack
