- packages/database/src/repository/User.ts
- packages/database/tests/degree.test.ts
- packages/database/tests/user.test.ts
Closes #46. Options 2-4 will be implemented in another PR as an additional config on User.eligibleModuels
User.eligibleModules currently only returns modules whose pre-reqs are cleared explicitly. So it does not include most level 1k/2k modules which are SU-able. Ideally there is an option for the user to choose whether they want to include such modules in their search.
1. No option for user (Current)
2. Assume that only modules with blank pre-requisites can be taken by anyone (Efficient, Inaccurate e.g. language modules, ES2660)
3. Assume that all SU-able modules can be taken by anyone (Inefficient, Inaccurate e.g. language modules, mods with MA1301 as pre-req)
4. Use prereqTree to check for prior modules (Inefficient, least inaccurate e.g. language modules, mods with special pre-reqs …
> User methods

- packages/database/src/repository/Graph.ts
- packages/database/tests/base/defined.test.ts
- packages/database/tests/degree/initialize.test.ts
- packages/database/tests/graph/initialize/pull-all.test.ts
- packages/database/tests/graph/suggest/from-one.test.ts
- packages/database/tests/module-condensed/fetch.test.ts
- packages/database/tests/module/pull.test.ts
- packages/database/tests/user/canTakeModule/add-module-codes.test.ts
- packages/database/tests/user/canTakeModule/no-optional-params.test.ts
- packages/database/tests/user/eligibleModules/add-module-codes.test.ts
- packages/database/tests/user/eligibleModules/no-optional-params.ts
- packages/database/tests/user/getPostReqs/add-module-codes.test.ts
- packages/database/tests/user/getPostReqs/no-optional-params.test.ts
- packages/database/tests/user/getUnlockedModules.test.ts
- packages/database/tests/user/initialize.test.ts
- packages/database/types/repository.d.ts
Clears all our tasks tagged as check
- Write `GraphRepository.findOneById`
- Add `Graph`, `GraphRepository` defined checks to tests
- `toEqual` -> `toStrictEqual` for sorted array checks in tests
- Remove repeated `User.initialize` tests, and instead have a test specifically for it
- `User.initialize` and `Degree.initialize` have find tests to confirm that the newly initialized entity is indeed in the DB
> Misc refactors + GraphRepository.findOneById

- apps/web/components/Views.tsx
- apps/web/components/buttons/FloatingUserButton/SignedIn.tsx
- apps/web/components/buttons/FloatingUserButton/SignedOut.tsx
- apps/web/components/modals/UserProfile.tsx
- apps/web/components/modals/UserProfile/SavedGraphs.tsx
- apps/web/components/modals/UserProfile/index.tsx
- apps/web/styles/globals.css
- apps/web/tailwind.config.js
- apps/web/tsconfig.json
- apps/web/ui/buttons.tsx
- mostly a proof-of-concept for other neighboring fields too
- `yarn serve` -> localhost:3000 -> Sign in -> User button -> Your Profile. It should show a fancy list of saved graphs.
> feat(frontend): add saved graphs to user profile modal

- libs/repo-graph/jest.config.ts
- libs/repo-graph/test/suggest/from-all.test.ts
- libs/repo-graph/test/suggest/from-one.test.ts
- libs/repo-module/jest.config.ts
- libs/repo-module/test/module/canTakeModule.test.ts
- libs/repo-module/test/module/getSuggestedModules/from-many.test.ts
- libs/repo-module/test/module/getSuggestedModules/from-one.test.ts
- libs/repo-module/test/pull/module-condensed.test.ts
Sets default jest test timeout to 15s for `repo-graph` and `repo-user`
- so that if we have somewhat long tests, we don't have to do `jest.setTimeout(xxxx)`
- 15s is chosen, because most of our setTimeouts are <=15s (10s or 15s)
Not very sure if this is a useful change.
Initialize `libs/repo-graph/test/long.test.ts` as follows. The test should fail due to exceeding the default timeout of 15000ms.
```
test('exceeds threshold', async () => {
return new Promise((resolve) => {
setTimeout(() => resolve(1), 16000);
});
})
```
Interestingly, jest currently does not catch infinite loops as per [this issue](https://github.com/facebook/jest/issues/10538), so you can't test with an infinite loop.
> test: jest timeouts

- libs/repo-user/src/index.ts
- libs/repo-user/test/setModuleStatus.test.ts
- libs/typeorm-config/src/data-source.ts
- libs/types/src/repository.ts
Creates `User.setModuleStatus`, to set a module as done, doing, or not taken. In preparation for the controller, which will be used in our right click menu
User tests should pass
> feat: User.setModuleStatus

- libs/postman/.gitignore
- libs/postman/degree/create.ts
- libs/postman/degree/delete.ts
- libs/postman/degree/list.ts
- libs/postman/graph/create.ts
- libs/postman/graph/delete.ts
- libs/postman/graph/list.ts
- libs/postman/package.json
- libs/postman/postman.config.json
- libs/postman/postman.ts
- libs/postman/tsconfig.json
- libs/postman/user/create.ts
- libs/postman/user/delete.ts
- libs/postman/user/get-full.ts
- libs/postman/user/get.ts
- libs/postman/user/insert-degree.ts
- libs/postman/user/list.ts
- postman but now it also takes cli arguments so we don't have to edit the files each time ids change.
```
yarn <entity>:<action> <positional args>
```
Reads ids whenever it's clearly necessary (such as when creating a graph, it needs user id and degree id).
```
yarn user:delete dcc3b6ff-669a-475a-819f-d5e5a3e68d5c
```
Other commands don't need ids
```
yarn degree:list
```
As usual, there are aliases for everything.
`yarn graph:create` is aliases to `yarn gc`
> feat: postman from v0.1.0 + some improvements

- apps/web/components/buttons/FloatingUserButton/MenuLink.tsx
- apps/web/components/buttons/FloatingUserButton/SignedIn.tsx
- apps/web/components/buttons/FloatingUserButton/SignedOut.tsx
- apps/web/components/buttons/FloatingUserButton/UserMenu.tsx
- apps/web/components/buttons/FloatingUserButton/UserMenuItems.tsx
- apps/web/components/modals/Debug/index.tsx
- apps/web/pages/index.tsx
- apps/web/store/modal.ts
- apps/web/types/index.d.ts
- for `NODE_ENV` as `development`, there will be an extra option in the user menu: Debug.
- Currently shows the contents of `useUser().user`, the user of the useUser hook.
- sign out and sign in and see if the `modtree` key of the user in the debug modal is populated.
> feat(frontend): add a debug modal

- apps/docs/data/degree/get.ts
- apps/docs/data/graph/get.ts
- apps/docs/data/module-condensed/get.ts
- apps/docs/data/module/get.ts
- apps/docs/data/user/get.ts
- apps/docs/types.d.ts
- apps/docs/utils/index.ts
- apps/docs/utils/schema.ts
- Created util that generates schema given example response
- Used util in all current API docs
- Updated User get and Graph get responses
I tried some libraries, but I felt that we just need something simple, so we can write our own util.
1. [generate-schema](https://www.npmjs.com/package/generate-schema)
- Doesn't seem to work well with TypeScript. I couldn't get it to work
2. [json-schema-generator](https://www.npmjs.com/package/json-schema-generator)
- I got it to return a schema, but it wasn't able to detect array contents.
- The schema produced is quite verbose, not clear what I can configure
- Compare example responses and the schemas
- Compare example responses in docs and responses from postman
> feat: generating schema from example response

- apps/web/components/modals/UserProfile/ModulesDone.tsx
- apps/web/store/base.ts
- rewrite redux function `getModulesCondensed` in a way that allows for the standard call of `dispatch(setModulesCondensed(modules))`.
> feat: use redux builtin reducer for setModuleCondensed

- apps/docs/data/graph/flow.ts
- apps/docs/data/graph/toggle.ts
- apps/docs/data/user/insert-degrees.ts
- apps/docs/types.d.ts
- apps/server/src/routes.ts
- apps/server/test/graphs/:graphId/flow/[PATCH].test.ts
- apps/server/test/graphs/:graphId/toggle/:moduleCode/[PATCH].test.ts
- apps/server/test/users/:userId/degrees/[PATCH].test.ts
- libs/postman/package.json
- libs/postman/postman.ts
- libs/postman/users/insert-degrees.ts
- `POST` is now used only for user login, and entity creation
- `PATCH` is used for updates to existing entities, where the client only specifies a partial entity.
- Server tests
- Frontend should not be affected
> refactor(api): use PATCH instead of POST where appropriate

- apps/server/src/api/user.ts
- apps/server/src/routes.ts
- apps/server/test/user/:userId/module/[PATCH].test.ts
- libs/repo-user/src/index.ts
- libs/repo-user/test/set-module-status.test.ts
- libs/types/src/repository.ts
- `User.setModuleStatus` now takes in an array of module codes, instead of a single module code
- Route at `user/:userId/module`
- Update repo test to send an array instead of a single module code
- Add test for server endpoint
> feat(api): set module status

- libs/repo-base/src/delete-all.ts
- libs/repo-graph/src/index.ts
- libs/repo-module/src/ModuleCondensed.ts
- libs/repo-user/src/index.ts
- libs/types/src/repository.ts
- If an entity is passed in as an argument to a repo method, the method will not use its id to retrieve a fresh copy from the database
> feat: repo methods don't retrieve entities from db

- apps/server/src/api/module-condensed.ts
- apps/server/test/modules-condensed/[GET].test.ts
- apps/web/components/user-profile/modules/add-doing.tsx
- apps/web/components/user-profile/modules/add-done.tsx
- apps/web/components/user-profile/modules/main.tsx
- apps/web/store/cache.ts
- apps/web/utils/backend.ts
- apps/web/utils/modules-condensed-cache.ts
> BREAKING: `GET /modules-condensed` will now return an empty array if `req.query.moduleCodes` is empty array. 
>
> Previously, it returns every module. Reason being that axios doesn't support sending empty arrays, and query params has only one legit data type (string).
>
> Axios will exclude `req.query.moduleCode` entirely if it's `[]`. So if the frontend requests with an empty array, the backend sees it as `undefined`.
- there exists a redux state to hold cached condensed modules
- `@/utils/modules-condensed-cache.ts` wraps this state with an async loader
> feat(frontend): cache management for module condensed

- apps/server/src/api/degree.ts
- apps/server/src/api/graph.ts
- apps/server/src/api/module-condensed.ts
- apps/server/test/degrees/[GET].test.ts
- apps/server/test/graphs/[GET].test.ts
- apps/server/test/modules-condensed/[GET].test.ts
- Previously, calling `GET /modules-condensed` with 1 module in an array would return you 0 modules. This is fixed
- `GET /degrees` now supports array param. If not passed, returns 0 degrees.
- `GET /graphs` now supports array param. If not passed, returns 0 graphs.
Server testing
> feat(api): find by IDs for Degree and Graph

- apps/server/src/api/degree.ts
- apps/server/src/api/graph.ts
- apps/server/src/api/user.ts
- apps/web/components/user-profile/degrees/add-new.tsx
- apps/web/components/user-profile/degrees/edit.tsx
- apps/web/components/user-profile/degrees/main.tsx
- apps/web/components/user-profile/modules/add-doing.tsx
- apps/web/components/user-profile/modules/add-done.tsx
- apps/web/components/user-profile/modules/main.tsx
- apps/web/components/user-profile/modules/selected-modules.tsx
- apps/web/store/search.ts
- apps/web/store/types.d.ts
- apps/web/store/user.ts
- apps/web/ui/search/index.tsx
- libs/repo-user/src/index.ts
- libs/types/src/api-response.ts
- libs/utils/src/empty.ts
- libs/utils/src/entity/index.ts
- All API endpoints return unflattened entities
- Updated some redux types
- The type `ModtreeApiResponse.{Entity}` is the type `{Entity}`
- `EmptyResponseProps` are still flattened types
- Ensure that frontend still works the same way
> feat: unflatten API results

- apps/server/src/main.ts
- libs/typeorm-config/src/index.ts
- libs/typeorm-config/test/config.test.ts
- scripts/yarn.sh
- server is bundled with webpack, and sent to `dist` at root.
- since json configs are read from relative paths, they will not get read at all.
- but .env files are still read, somehow
so now frontend authenticates properly with server given this `.env` at workspace root:
```
POSTGRES_DATABASE=web
POSTGRES_USERNAME=web
POSTGRES_PASSWORD=web
POSTGRES_HOST=localhost
POSTGRES_PORT=4000
TEST_POSTGRES_DATABASE=test
TEST_POSTGRES_USERNAME=test
TEST_POSTGRES_PASSWORD=test
TEST_POSTGRES_HOST=localhost
TEST_POSTGRES_PORT=4001
```
- Mutate the given .env params and the connection should be denied.
> feat: add port reading to .env

- libs/auto-docs/test/setup.test.ts
Technically, #265 fixes issue #264 by excluding auto-docs from `yarn test`.
This PR prevents `references/api.json` from being overwritten if you specifically run `yarn nx test auto-docs`.
`yarn nx test auto-docs` should not overwrite `references/api.json`, if the server is not running
> fix: only run auto-docs when server is running

- apps/server/src/api/user.ts
- apps/web/api/graph.ts
- apps/web/components/menu-items.ts
- apps/web/components/modals/module-info/contents.tsx
- apps/web/utils/graph/index.ts
- libs/repos/src/graph/repo.ts
- In module info modal, "Add to graph" is hidden if the module is in `graph.modulesPlaced`
- "More info" context menu option is now functional
- "Remove" context menu option persists
- Search for a module that is already placed. The modal should not display "Add to graph"
- Click "More info" menu item for a placed module. The modal should not display "Add to graph"
- Remove a module from the graph. You should be able to add back the module immediately. Upon refresh, the removed module stays removed.
> feat: module context menu

- apps/server/src/routes.ts
- apps/web/api/graph.ts
- apps/web/components/menu-items.ts
- apps/web/components/modals/module-info/contents.tsx
- apps/web/components/user-profile/degrees/add-new.tsx
- apps/web/components/user-profile/degrees/edit.tsx
- apps/web/components/user-profile/degrees/main.tsx
- apps/web/store/graph.ts
- apps/web/ui/search/graph/pick-one.tsx
- apps/web/utils/rehydrate.ts
- libs/types/src/entities/Graph.ts
- Adding a node to graph now persists
- Try adding a node to the graph, and refresh the page.
- You should still see the node, and the nodes and edges are at the same positions.
- Note that the initial load time is **rather slow** due to a slow `/user/:userId/get-full`. You can take 30 seconds or more to load the user data, as mentioned in #293.
> feat: persist adding node to graph

- apps/server/src/api/degree.ts
- apps/server/src/api/graph.ts
- apps/server/src/api/user.ts
- apps/web/api/degree.ts
- apps/web/api/graph.ts
- apps/web/api/user.ts
- apps/web/components/user-profile/degrees/edit.tsx
- apps/web/components/user-profile/graphs/main.tsx
- apps/web/store/graph.ts
- apps/web/store/initial-state.ts
- apps/web/store/types.d.ts
- apps/web/ui/search/degree/degree-picker.tsx
- apps/web/ui/search/graph/graph-picker.tsx
- apps/web/utils/graph/index.ts
- apps/web/utils/graph/unique-title.spec.ts
- libs/types/src/api-response.ts
- libs/utils/src/empty-entity.ts
- libs/utils/src/entity/flatten.spec.ts
- libs/utils/src/entity/index.ts
- Retire `GraphFull` and related types
- Frontend `Graph` states do not have degree modules
- Frontend `Degree` has flattened modules
- Frontend API abstraction uses `ModtreeApiResponse` in all of its return types
- Minor refactoring
- Regular testing
> refactor: cleanup

- apps/web/components/user-profile/degrees/add-new.tsx
- apps/web/components/user-profile/modules/main.tsx
- apps/web/components/user-profile/modules/selected-modules.tsx
- As part of #320, user modules are flattened and we refer to cache.
- This change ensures that the module in cache is defined before trying to access
- Check add degrees panel, modules done/doing panel. The app should not crash.
> fix: check modules in cache defined

- apps/web-e2e/cypress/integration/modules.cy.ts
- apps/web/components/user-profile/modules/add-doing.tsx
- apps/web/components/user-profile/modules/add-done.tsx
- apps/web/components/user-profile/modules/main.tsx
- apps/web/components/user-profile/modules/selected-modules.tsx
- apps/web/ui/search/module/container.tsx
- apps/web/ui/search/module/index.tsx
- apps/web/ui/search/module/input.tsx
- apps/web/ui/settings/lists/base.tsx
Working towards #332
- Add e2e test for modules panel (add/remove modules done/doing)
- Add `data-cy` attribute on base HTML elements for the sole purpose of being selectors in cypress tests
- `yarn dev:server`
- `yarn e2e`
- Select `modules.cy.ts`
> test(e2e): modules panel

- apps/server/src/trpc/user.ts
- apps/web/components/menu-items.ts
- apps/web/components/user-profile/graphs/main.tsx
- libs/repos/src/user/repo.ts
- libs/types/src/repository.ts
- Can now remove graph. Not allowed to remove the main graph.
- Can set module as not done in the node context menu.
- Add a new graph. You should not be able to remove your set graph, but you can remove the other graph.
- Try setting a done/doing module as not done through the node context menu. It will be removed from user panel modules done/doing
> feat: remove graph, set module as not done

- apps/server/src/api/user.ts
- apps/server/src/trpc/user.ts
- apps/web-e2e/cypress/integration/graph/add-and-remove.cy.ts
- apps/web-e2e/cypress/support/commands.ts
- apps/web/api/degree.ts
- apps/web/api/user.ts
- apps/web/components/user-profile/degrees/main.tsx
- apps/web/components/user-profile/graphs/add-new.tsx
- apps/web/components/user-profile/graphs/main.tsx
- apps/web/components/user-profile/modules/main.tsx
- apps/web/store/degree.ts
- apps/web/store/initial-state.ts
- apps/web/store/types.d.ts
- apps/web/store/user.ts
- apps/web/ui/search/degree/degree-picker.tsx
- apps/web/ui/search/graph/graph-picker.tsx
- apps/web/utils/rehydrate.ts
- libs/types/src/api-response.ts
- libs/utils/src/empty-entity.ts
- libs/utils/src/entity/index.ts
- Add graph panel only shows title and degree
- Frontend user state uses flattened degrees (i.e. we are back to the original `ModtreeApiResponse.User`)
- Retire `ModtreeApiResponse.UserFull`
- e2e tests
- Edit Degree panel displays title and modules correctly
- Add Graph panel displays degree title correctly
> feat: flatten user degrees

- apps/web/api/module.ts
- apps/web/store/modal.ts
- and also reset it to original state once it's closed
> fix: only show module modal once data is loaded

- apps/web-e2e/cypress/fixtures/session.json
- apps/web-e2e/cypress/integration/user-profile/degrees.cy.ts
- apps/web-e2e/cypress/support/commands.ts
- apps/web/components/buttons/floating-user-button.tsx
- Use fake credentials for local testing (`yarn e2e`)
- Switch to `cypress-social-login` for remote testing (`yarn e2e:dev`, `yarn e2e:prod`)
- In degree test, use more accurate way to extract module to remove
Run E2E test on localhost. It should use the fake credentials, and be much faster
> test(e2e): use fake credentials for local testing

- apps/web/components/user-profile/degrees/add-new.tsx
- apps/web/components/user-profile/graphs/add-new.tsx
- apps/web/ui/buttons/text.tsx
- Fixes #362
- Button turns gray if disabled
- Go to `degrees/add-new.tsx`
- Locate the save function, and comment out `props.setPage("main")`, to temporarily disable redirect to main.
- Try to create a new degree. It does not redirect back to main, and you can see the button being disabled immediately.
- Repeat for `graphs/add-new.tsx`
> fix: prevent clicking save graph/degree multiple times

- apps/server/src/app.ts
- apps/web/utils/trpc.ts
- tRPC router is now mounted at `/trpc`.
- BREAKING: In `.env`, `NEXT_PUBLIC_BACKEND` should point to the new backend at `/trpc`. This includes the development and local deployments.
E2E tests pass locally
> feat: migrate base endpoint to `/trpc`

- apps/web-e2e/cypress/integration/graph/new-graph.cy.ts
- apps/web-e2e/cypress/support/commands.ts
- apps/web/components/flow/module-node.tsx
- apps/web/components/flow/nodes.tsx
- apps/web/components/flow/pane.tsx
- apps/web/components/modals/debug.tsx
- apps/web/components/modals/module-info/contents.tsx
- apps/web/types/index.d.ts
- apps/web/utils/module-state.ts
- libs/repos/src/graph/get-modules.ts
- libs/repos/src/graph/get-nodes.ts
- libs/repos/src/graph/repo.ts
- libs/types/src/flow.ts
- libs/utils/src/flow/get-nodes.ts
- use React Flow's `nodeType` to directly manage our core logic's module state
> feat: use node types to manage module state

- apps/web-e2e/cypress.config.js
- apps/web-e2e/cypress/integration/cypress-utils/redux.cy.ts
- apps/web-e2e/cypress/integration/graph/add-and-remove.cy.ts
- apps/web-e2e/cypress/integration/user-profile/degrees.cy.ts
- apps/web-e2e/cypress/support/app.po.ts
- apps/web-e2e/cypress/support/commands.ts
- apps/web-e2e/cypress/support/index.ts
- apps/web-e2e/cypress/support/login.ts
- apps/web-e2e/cypress/support/redux.ts
* packaged up redux state-getting in cypress tests
* to get graph state, for example:
```typescript
cy.reduxGraph().then((graph) => {
// do graph stuff here
}
```
* `cy.reduxUser()` and `cy.reduxDegree()` are also available
* add tests to make sure these state getters work
> test(e2e): add wait-less redux state getters

- apps/docs/public/openapi-docs.yml
- libs/trpc-openapi/src/generator/paths.ts
- libs/trpc-openapi/src/generator/schema.ts
Due to `trpc-openapi` implementation, YAML refs are currently not supported correctly. This patch supports YAML refs for our docs generation. As a result, there are no more console warns about recursive references.
- Build server and run it. There should not be any more recursive reference warnings
> feat: support relative YAML refs

- docker/cy-reporter/build.js
releasing a docker image built on an `arm` or `arm64` system will simply not run on Heroku's dyno.
> fix: only release heroku builds on non-arm systems

- libs/cy-reporter/dev.js
- libs/cy-reporter/src/cli/help.ts
- libs/cy-reporter/src/cli/index.ts
- libs/cy-reporter/src/cli/parse-args.ts
- libs/cy-reporter/src/cli/types.d.ts
- libs/cy-reporter/src/reporters/sender.ts
- package.json
- package.scripts.js
- scripts/run-tests/help.ts
- scripts/runner.js
Working towards #406
- `yarn cy open` now opens Cypress GUI
- `yarn cy` help text reflects this
- dev tools that use `webpack` watch feature now awaits the first build before starting.
- this eliminates the error shown when the server starts when the build output doesn't exist yet.
> feat: open cypress GUI from `yarn cy`
